<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateNurserySchoolsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('nursery_schools', function(Blueprint $t){
            $t->bigIncrements('id')->comment('ID');
            $t->bigInteger('facility_cd')->comment('施設コード');
            $t->string('name',255)->comment('名称');
            $t->string('name_kana',255)->nullable()->comment('名称（かな）');
            $t->string('zip_cd',7)->comment('郵便番号（郵便区番号+町域番号）');
            $t->string('pref_cd',2)->comment('都道府県コード');
            $t->string('city_cd',6)->comment('市区町村コード');
            $t->string('block_number_address',255)->nullable()->comment('番地');
            $t->string('building_address',255)->nullable()->comment('ビル・建物名');
            $t->bigInteger('nearest_station_cd_1')->nullable()->comment('最寄駅1コード');
            $t->bigInteger('nearest_station_cd_2')->nullable()->comment('最寄駅2コード');
            $t->bigInteger('nearest_station_cd_3')->nullable()->comment('最寄駅3コード');
            $t->string('transportation_1',255)->nullable()->comment('交通手段１');
            $t->string('transportation_2',255)->nullable()->comment('交通手段２');
            $t->string('transportation_3',255)->nullable()->comment('交通手段３');
            $t->string('operating_company',255)->nullable()->comment('運営会社');
            $t->string('establishment',255)->nullable()->comment('設立年');
            $t->string('home_page',255)->nullable()->comment('ホームページ');
            $t->string('phone_number',16)->comment('電話番号（市外局番）');
            $t->boolean('is_authorization')->comment('認可')->default(false);
            $t->boolean('is_authentication')->comment('認証')->default(false);
            $t->boolean('is_not_authorization')->comment('認可外')->default(false);
            $t->string('auth_etc',255)->nullable()->comment('その他');
            $t->boolean('is_public_nursery')->comment('公立保育園')->default(false);
            $t->boolean('is_private_nursery')->comment('私立保育園')->default(false);
            $t->boolean('is_notauthorize')->comment('認可外保育園')->default(false);
            $t->boolean('is_children_garden')->comment('認定こども園')->default(false);
            $t->boolean('is_authenticated_type_a')->comment('認証保育園A型')->default(false);
            $t->boolean('is_authenticated_type_b')->comment('認証保育園B型')->default(false);
            $t->boolean('is_small_scale_type_a')->comment('小規模保育A型')->default(false);
            $t->boolean('is_small_scale_type_b')->comment('小規模保育B型')->default(false);
            $t->boolean('is_small_scale_type_c')->comment('小規模保育C型')->default(false);
            $t->boolean('is_domestic')->comment('家庭的保育')->default(false);
            $t->string('nursery_etc',255)->nullable()->comment('その他');
            $t->boolean('extended_morning_flg')->comment('7時〜OK（朝延長あり）')->default(false);
            $t->boolean('extended_evening_flg')->comment('18時〜OK（夜延長あり）')->default(false);
            $t->boolean('up_to_two_flg')->comment('2歳まで')->default(false);
            $t->boolean('up_to_five_flg')->comment('5歳まで')->default(false);
            $t->boolean('saturday_care_flg')->comment('土曜保育')->default(false);
            $t->boolean('allergic_response_flg')->comment('アレルギー対応')->default(false);
            $t->binary('image_1')->nullable()->comment('画像１');
            $t->binary('image_2')->nullable()->comment('画像２');
            $t->binary('image_3')->nullable()->comment('画像３');
            $t->binary('image_4')->nullable()->comment('画像４');
            $t->binary('image_5')->nullable()->comment('画像５');
            $t->datetime('basic_open_time')->nullable()->comment('基本開園時間（時分）');
            $t->datetime('basic_close_time')->nullable()->comment('基本閉園時間（時分）');
            $t->datetime('extended_morning_start_time')->nullable()->comment('早朝保育開始時間（時分）');
            $t->datetime('extended_morning_close_time')->nullable()->comment('早朝保育終了時間（時分）');
            $t->datetime('extended_evening_start_time')->nullable()->comment('延長保育開始時間（時分）');
            $t->datetime('extended_evening_close_time')->nullable()->comment('延長保育終了時間（時分）');
            $t->string('closed_day',255)->nullable()->comment('休園日');
            $t->integer('building_area')->nullable()->comment('建物（平方メートル）');
            $t->enum('with_garden',['なし','あり'])->comment('園庭の有無');
            $t->integer('garden_area')->nullable()->comment('園庭（平方メートル）');
            $t->enum('with_launch',['なし','あり'])->comment('給食の有無');
            $t->enum('with_allergic_response',['対応なし','除去食あり','代替食あり','個別相談'])->comment('アレルギー対応の有無');
            $t->enum('with_frozen_milk',['なし','あり'])->comment('冷凍母乳の対応の有無');
            $t->string('accept_age')->nullable()->comment('受け入れ開始年齢');
            $t->integer('capacity_zero')->nullable()->comment('定員：0才');
            $t->integer('capacity_one')->nullable()->comment('定員：1才');
            $t->integer('capacity_two')->nullable()->comment('定員：2才');
            $t->integer('capacity_three')->nullable()->comment('定員：3才');
            $t->integer('capacity_five')->nullable()->comment('定員：5才');
            $t->integer('capacity_six')->nullable()->comment('定員：6才');
            $t->integer('permanent_head_num')->nullable()->comment('常任職員数：園長');
            $t->integer('permanent_sub_head_num')->nullable()->comment('常任職員数：副園長');
            $t->integer('permanent_childminder_num')->nullable()->comment('常任職員数：保育士');
            $t->integer('permanent_childminder_assistance_num')->nullable()->comment('常任職員数：保育補助');
            $t->integer('permanent_nurse_num')->nullable()->comment('常任職員数：看護師');
            $t->integer('permanent_dietician_num')->nullable()->comment('常任職員数：栄養士');
            $t->integer('permanent_cooks_num')->nullable()->comment('常任職員数：調理');
            $t->integer('permanent_clerk_num')->nullable()->comment('常任職員数：用務員');
            $t->integer('part_time_head_num')->nullable()->comment('非常任職員数：園長');
            $t->integer('part_time_sub_head_num')->nullable()->comment('非常任職員数：副園長');
            $t->integer('part_time_childminder_num')->nullable()->comment('非常任職員数：保育士');
            $t->integer('part_time_childminder_assistance_num')->nullable()->comment('非常任職員数：保育補助');
            $t->integer('part_time_nurse_num')->nullable()->comment('非常任職員数：看護師');
            $t->integer('part_time_dietician_num')->nullable()->comment('非常任職員数：栄養士');
            $t->integer('part_time_cooks_num')->nullable()->comment('非常任職員数：調理');
            $t->integer('part_time_clerk_num')->nullable()->comment('非常任職員数：用務員');
            $t->text('educational_policy')->nullable()->comment('教育方針');
            $t->text('featured_event')->nullable()->comment('特色のある行事');
            $t->text('emphasize_thing')->nullable()->comment('特に力を入れていること');
            $t->enum('with_parent_association',['なし','あり','その他'])->comment('保護者会の有無');
            $t->string('parent_association_etc',255)->nullable()->comment('保護者会：その他');
            $t->enum('with_parking',['なし','あり','その他'])->comment('駐車場の有無');
            $t->string('parking_etc',255)->nullable()->comment('駐車場：その他');
            $t->enum('with_bicyle_parking',['なし','あり','その他'])->comment('駐輪場の有無');
            $t->string('bicycle_etc',255)->nullable()->comment('駐輪場：その他');
            $t->enum('with_stroller_storage',['なし','あり','その他'])->comment('ベビーカー置き場の有無');
            $t->string('stroller_storage_etc',255)->nullable()->comment('ベビーカー置き場：その他');
            $t->enum('with_takeout_diaper',['なし','あり','その他'])->comment('おむつの持ち帰りの有無');
            $t->string('takeout_diaper_etc')->nullable()->comment('おむつの持ち帰り：その他');
            $t->text('howto_spend_jan')->nullable()->comment('1月');
            $t->text('howto_spend_feb')->nullable()->comment('2月');
            $t->text('howto_spend_mar')->nullable()->comment('3月');
            $t->text('howto_spend_apr')->nullable()->comment('4月');
            $t->text('howto_spend_may')->nullable()->comment('5月');
            $t->text('howto_spend_jun')->nullable()->comment('6月');
            $t->text('howto_spend_jul')->nullable()->comment('7月');
            $t->text('howto_spend_aug')->nullable()->comment('8月');
            $t->text('howto_spend_sep')->nullable()->comment('9月');
            $t->text('howto_spend_oct')->nullable()->comment('10月');
            $t->text('howto_spend_nov')->nullable()->comment('11月');
            $t->text('howto_spend_dec')->nullable()->comment('12月');
            $t->datetime('howto_spend_time_1')->nullable()->comment('時分_1');
            $t->text('howto_spend_baby_1')->nullable()->comment('乳児_内容_1');
            $t->text('howto_spend_infant_1')->nullable()->comment('幼児_内容_1');
            $t->datetime('howto_spend_time_2')->nullable()->comment('時分_2');
            $t->text('howto_spend_baby_2')->nullable()->comment('乳児_内容_2');
            $t->text('howto_spend_infant_2')->nullable()->comment('幼児_内容_2');
            $t->datetime('howto_spend_time_3')->nullable()->comment('時分_3');
            $t->text('howto_spend_baby_3')->nullable()->comment('乳児_内容_3');
            $t->text('howto_spend_infant_3')->nullable()->comment('幼児_内容_3');
            $t->datetime('howto_spend_time_4')->nullable()->comment('時分_4');
            $t->text('howto_spend_baby_4')->nullable()->comment('乳児_内容_4');
            $t->text('howto_spend_infant_4')->nullable()->comment('幼児_内容_4');
            $t->datetime('howto_spend_time_5')->nullable()->comment('時分_5');
            $t->text('howto_spend_baby_5')->nullable()->comment('乳児_内容_5');
            $t->text('howto_spend_infant_5')->nullable()->comment('幼児_内容_5');
            $t->datetime('howto_spend_time_6')->nullable()->comment('時分_6');
            $t->text('howto_spend_baby_6')->nullable()->comment('乳児_内容_6');
            $t->text('howto_spend_infant_6')->nullable()->comment('幼児_内容_6');
            $t->datetime('howto_spend_time_7')->nullable()->comment('時分_7');
            $t->text('howto_spend_baby_7')->nullable()->comment('乳児_内容_7');
            $t->text('howto_spend_infant_7')->nullable()->comment('幼児_内容_7');
            $t->datetime('howto_spend_time_8')->nullable()->comment('時分_8');
            $t->text('howto_spend_baby_8')->nullable()->comment('乳児_内容_8');
            $t->text('howto_spend_infant_8')->nullable()->comment('幼児_内容_8');
            $t->datetime('howto_spend_time_9')->nullable()->comment('時分_9');
            $t->text('howto_spend_baby_9')->nullable()->comment('乳児_内容_9');
            $t->text('howto_spend_infant_9')->nullable()->comment('幼児_内容_9');
            $t->datetime('howto_spend_time_10')->nullable()->comment('時分_10');
            $t->text('howto_spend_baby_10')->nullable()->comment('乳児_内容_10');
            $t->text('howto_spend_infant_10')->nullable()->comment('幼児_内容_10');
            $t->datetime('howto_spend_time_11')->nullable()->comment('時分_11');
            $t->text('howto_spend_baby_11')->nullable()->comment('乳児_内容_11');
            $t->text('howto_spend_infant_11')->nullable()->comment('幼児_内容_11');
            $t->datetime('howto_spend_time_12')->nullable()->comment('時分_12');
            $t->text('howto_spend_baby_12')->nullable()->comment('乳児_内容_12');
            $t->text('howto_spend_infant_12')->nullable()->comment('幼児_内容_12');
            $t->datetime('howto_spend_time_13')->nullable()->comment('時分_13');
            $t->text('howto_spend_baby_13')->nullable()->comment('乳児_内容_13');
            $t->text('howto_spend_infant_13')->nullable()->comment('幼児_内容_13');
            $t->datetime('howto_spend_time_14')->nullable()->comment('時分_14');
            $t->text('howto_spend_baby_14')->nullable()->comment('乳児_内容_14');
            $t->text('howto_spend_infant_14')->nullable()->comment('幼児_内容_14');
            $t->datetime('howto_spend_time_15')->nullable()->comment('時分_15');
            $t->text('howto_spend_baby_15')->nullable()->comment('乳児_内容_15');
            $t->text('howto_spend_infant_15')->nullable()->comment('幼児_内容_15');
            $t->boolean('is_pr')->comment('優先表示枠チェック')->default(false);
            $t->boolean('is_public')->comment('公開')->default(false);
            $t->datetime('public_start_dtm')->comment('掲載開始日時（yyyyMMddhhmm)');
            $t->datetime('public_end_dtm')->comment('掲載終了日時（yyyyMMddhhmm)');
            $t->integer('favorited_num')->comment('あとで見る登録数')->default(0);
            $t->timestamps();
            $t->softDeletes();
        });
        DB::statement('alter table nursery_schools add location geometry');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('nursery_schools');
    }
}
